# https://github.com/dannyben/opcode

## Development

watch: retype start -n
#? watch src folder and rebuild on change

preview: httpme docs
#? serve the static site with httpme

build: rm -rfv docs/* ; retype build
#? clear target dir and rebuild site

## Testing

test: test/test.sh
#? run tests

spell: typos
#? run spellcheck tests

sla: test/broken_links.sh
#? run site link analyzer



# Unused

# run: foreman start
#? watch and serve

# watch: filewatcher --immediate src "op build"
#? watch src folder and rebuild on change